apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: ingress-nginx
  labels:
    k8s-app: haproxy
spec:
  type: ClusterIP  
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000  
   
---
apiVersion: v1
kind: Endpoints
metadata:
  name: haproxy
  namespace: ingress-nginx
  labels:
    k8s-app: haproxy
subsets:
- addresses:
  - ip: 10.0.0.100
  ports:
  - name: http
    port: 9000
    protocol: TCP  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy
  namespace: ingress-nginx
  annotations:
    external-dns.alpha.kubernetes.io/target: "lb.${SECRET_DOMAIN_2}"    
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start
spec:
  rules:
  - host: haproxy.${SECRET_DOMAIN_2}
    http:
      paths:
      - backend:
          service:
            name: haproxy
            port: 
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - haproxy.${SECRET_DOMAIN_2}
