---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 1h
  chart:
    spec:
      chart: rancher-monitoring
      version: 100.1.2+up19.0.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  values:
    grafana:
      nodeSelector:
        kubernetes.io/arch: amd64
      persistence:
        enabled: "true"
        accessModes:
          - ReadWriteMany
        storageClassName: longhorn-backup
        size: 1Gi
        subPath: null
        type: pvc
    prometheus:
      prometheusSpec:
        resources:
          limits:
            cpu: 1000m
            memory: 6000Mi
          requests:
            cpu: 750m
            memory: 4000Mi
        nodeSelector:
          kubernetes.io/arch: amd64
#        storageSpec:
#          volumeClaimTemplate:
#            spec:
#              accessModes:
#                - ReadWriteMany
#              resources:
#                requests:
#                  storage: 15Gi
#              volumeMode: Filesystem
#              storageClassName: longhorn
        thanos:
          image: quay.io/thanos/thanos:v0.27.0
          version: v0.24.0
          objectStorageConfig:
            name: thanos-objstore-secret
            key: objstore.yml
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      thanosIngress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start
          external-dns.alpha.kubernetes.io/hostname: "thanos-gateway.${SECRET_DOMAIN_2}"
          external-dns.alpha.kubernetes.io/ttl: "120"
          external-dns.alpha.kubernetes.io/target: "lb.${SECRET_DOMAIN_2}"
        hosts: 
          - thanos-gateway.${SECRET_DOMAIN_2}
        pathType: ImplementationSpecific
        tls: 
         - hosts:
           - thanos-gateway.${SECRET_DOMAIN_2}


