---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 1h
  chart:
    spec:
      chart: rancher-monitoring
      version: 100.1.2+up19.0.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  values:
    grafana:
      nodeSelector:
        kubernetes.io/arch: amd64
      persistence:
        enabled: "true"
        accessModes:
          - ReadWriteMany
        storageClassName: longhorn-backup
        size: 1Gi
        subPath: null
        type: pvc
      sidecar:
        datasources:
          enabled: true
          searchNamespace: ALL
          # defaultDatasourceEnabled: false
        dashboards:
          enabled: true
          searchNamespace: ALL
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          1-node-exporter:
            url: https://grafana.com/api/dashboards/11074/revisions/9/download
            datasource: Prometheus
          blocky:
            url: https://raw.githubusercontent.com/0xERR0R/blocky/v0.18/docs/blocky-grafana.json
            datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/2842          
          flux-cluster:
            url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
            datasource: Prometheus
          flux-control-plane:
            url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
            datasource: Prometheus
          home-assistant:
            url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/home_assistant.json
            datasource: home_assistant
          loki:
            gnetId: 13407
            revision: 1
            datasource: Prometheus
          minio-overview:
            url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/minio_overview.json
            datasource: Prometheus
          nginx-dashboard:
            url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
            datasource: Prometheus
          node-exporter-full:
            gnetId: 1860
            revision: 23
            datasource: Prometheus
          prometheus-exporter-summary:
            url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/prometheus_exporter_summary.json
            datasource: Prometheus          
          # Ref: https://grafana.com/grafana/dashboards/11312          
          velero:
            url: https://grafana.com/api/dashboards/11055/revisions/2/download
            datasource: Prometheus          
    prometheus:
      prometheusSpec:
        resources:
          limits:
            cpu: 1000m
            memory: 6000Mi
          requests:
            cpu: 750m
            memory: 4000Mi
        nodeSelector:
          kubernetes.io/arch: amd64
#        storageSpec:
#          volumeClaimTemplate:
#            spec:
#              accessModes:
#                - ReadWriteMany
#              resources:
#                requests:
#                  storage: 15Gi
#              volumeMode: Filesystem
#              storageClassName: longhorn
        thanos:
          image: quay.io/thanos/thanos:v0.27.0
          version: v0.24.0
          objectStorageConfig:
            name: thanos-objstore-secret
            key: objstore.yml
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      thanosIngress:
        enabled: false
        