kind: Deployment
apiVersion: apps/v1
metadata:  
  name: cloudflare-ddns-domain3
  namespace: networking
  labels:
    app: cloudflare-ddns
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      nodeSelector:         
        location: onprem
      containers:
      - name: cloudflare-ddns
        image: oznu/cloudflare-ddns:amd64  
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        - name: ZONE
          value: ${SECRET_DOMAIN_3}
        - name: SUBDOMAIN
          value: "ipv4"
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi