---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0

#    env:
#      TZ: "${TZ}"

    hajimari:
      namespaceSelector:
        matchNames:
          - home
          - home-automation
          - media
          - monitoring
          - network
          - rook-ceph
      customApps:
        - name: UnRaid
          url: "http://tower.${SECRET_DOMAIN}"
          icon: nas
        - name: opnSense
          url: "https://gw01.${SECRET_DOMAIN}"
          icon: router
        - name: AdGuardHome
          url: "http://gw01.${SECRET_DOMAIN}:3010"
          icon: shield-home
        - name: Zigbee2mqtt
          url: "http://zigbee.${SECRET_DOMAIN}:8080"
          icon: zigbee
        - name: PGAdmin
          url: "https://pgadmin.${SECRET_DOMAIN}"
          icon: database-cog
        - name: UniFi
          url: "https://unifi.${SECRET_DOMAIN}:8443"
          icon: network
      groups:
        - name: Social Media
          links:
            - name: Instagram
              url: 'https://instagram.com'
            - name: Tweetdeck
              url: 'https://tweetdeck.twitter.com/'
        - name: Tesla
          links:
            - name: Tronity
              url: 'https://app.tronity.io/dashboard'
            - name: TFF-Forum
              url: 'https://tff-forum.de'
        - name: Photovoltaik
          links:
            - name: Kostal Portal
              url: 'https://www.kostal-solar-portal.com/#/site/206273/dashboard/'
        - name: Design
          links:
            - name: SimpleIcons
              url: 'https://simpleicons.org/'
            - name: Material Design Icons
              url: 'https://materialdesignicons.com/'

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "lb.${SECRET_DOMAIN_2}" 
          external-dns.alpha.kubernetes.io/ttl: "120" 
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start
        hosts:
          - host: "hajimari.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - hajimari.${SECRET_DOMAIN_2}

    persistence:
      data:
        enabled: true
        existingClaim: hajimari-data-v1

    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 35m
        memory: 105M

