---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-crd
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: longhorn-crd
      version: 100.2.2+up1.3.1
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  