---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-v1
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
