---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: paperless
      version: 8.8.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/paperless/values.yaml
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: ngx-1.7.0

    env:      
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: "Europe/Berlin"
      PAPERLESS_CONSUMER_POLLING: "60"
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_DBHOST: localhost
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless

    persistence:
      data:
        enabled: true
        existingClaim: paperless-data-v1
      media:
        enabled: true
        existingClaim: paperless-media-v1
      consume:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.0.3"
            path: /nas02/shares/dms-import
        mountPath: /usr/src/paperless/consume
      export:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.0.3"
            path: /nas02/shares/dms-export
        mountPath: /usr/src/paperless/export

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dms.${SECRET_DOMAIN_2}" 
          external-dns.alpha.kubernetes.io/ttl: "120" 
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
          - host: "dms.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "dms.${SECRET_DOMAIN_2}"

    resources:
      requests:
        cpu: 10m
        memory: 379M
      limits:
        cpu: 73m
        memory: 1218M

    # -- Enable and configure postgresql database subchart under this key.
    #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
    # @default -- See values.yaml
    postgresql:
      enabled: true
      postgresqlUsername: paperless
      postgresqlPassword: paperless
      postgresqlDatabase: paperless
      persistence:
        enabled: true
        storageClass: "longhorn"

    # -- Enable and configure redis subchart under this key.
    #    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
    # @default -- See values.yaml
    redis:
      enabled: true
      auth:
        enabled: false