---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-v1
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: nfs-client
