---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 100.2.2+up1.3.1
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 1
      defaultClass: false