---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph
      version: v1.9.6
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system

  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5


  values:
    crds:
      enabled: false

    monitoring:
      enabled: true

    csi:
      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
