dns_server_ip: 192.168.0.1

harden_linux_ufw_rules:
  - rule: "allow"
    to_port: "22"
    protocol: "tcp"
  - rule: "allow"
    to_port: "51820"
    protocol: "udp"

harden_linux_ufw_allow_networks:
  - "10.0.0.0/24"  
  - "10.42.0.0/24"  
  - "10.43.0.0/24"  

harden_linux_ufw_defaults_user:
  "^DEFAULT_FORWARD_POLICY": 'DEFAULT_FORWARD_POLICY="ACCEPT"'

harden_linux_sysctl_settings_user:
  "net.ipv4.ip_forward": 1                         # Do not allow traffic between networks or act as a router
  "net.ipv6.conf.all.forwarding": 1                # IPv6 - Do not allow traffic between networks or act as a router
#  "net.ipv4.conf.all.accept_source_route": 1       # Ignore source-routed packets
#  "net.ipv6.conf.all.accept_source_route": 1       # IPv6 - Ignore ICMP redirects
#  "net.ipv4.conf.default.accept_source_route": 1   # Ignore source-routed packets
#  "net.ipv6.conf.default.accept_source_route": 1   # IPv6 - Ignore source-routed packets
#  "net.ipv4.conf.all.accept_redirects": 1          # Ignore ICMP redirects
#  "net.ipv6.conf.all.accept_redirects": 1          # IPv6 - Ignore ICMP redirects
#  "net.ipv4.conf.default.accept_redirects": 1      # Ignore ICMP redirects
#  "net.ipv6.conf.default.accept_redirects": 1      # IPv6 - Ignore ICMP redirects
#  "net.ipv4.conf.all.secure_redirects": 1          # Ignore ICMP redirects from non-GW hosts
#  "net.ipv4.conf.default.secure_redirects": 1      # Ignore ICMP redirects from non-GW hosts

harden_linux_ufw_logging: 'on'

postgresql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63323961363733383439636461363337613461656135303837356438386633653463393330613831
          3966616130626661346330363632363631613633613238320a356533656461396530313931636464
          66353030343938313938333936303539373831663931643932366635366431373861613562366461
          3733373865333361650a393833306261616537326331396266613332353734313166336233613866
          39343135646631393231623361653766333765376139613330343332353431323738


postgresql_databases:
  - name: k3s
postgresql_users:
  - name: k3s
    password: "{{ postgresql_password }}"

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '10.0.0.0/24', auth_method: "{{ postgresql_auth_method }}"}

postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: listen_addresses
    value: '10.0.0.100'    


#wireguard_allowed_ips: "10.0.0.0/24"

wireguard_unmanaged_peers:
  mac:
    public_key: V25CgJg2DNw31r7z/U4JGnSK5skcHA5EvP8H0HDNUXc=
    # preshared_key: ... e.g. from ansible-vault?
    allowed_ips: 10.0.0.199/32
    #endpoint: ""
    persistent_keepalive: 25