k3s_state: installed
k3s_release_version: v1.23.7+k3s1
k3s_become: true
k3s_build_cluster: true

# i really want only one master node. :-)
k3s_use_unsupported_config: true

k3s_server:
  datastore-endpoint: "postgres://k3s:{{ postgresql_password }}@10.0.0.100:5432/k3s?sslmode=disable"
  flannel-iface: 'wg0'
  node-taint: 
    - 'node-role.kubernetes.io/master=true:NoSchedule'
    - 'node-role.kubernetes.io/control-plane=true:NoSchedule'
  disable:
    - local-storage
    - traefik
    - servicelb
  tls-san: 10.0.0.100

#k3s_server_manifests_urls:
#  - url: https://kube-vip.io/manifests/rbac.yaml
#    filename: kube-vip-rbac.yaml

#k3s_server_manifests_templates:
#  - "manifests/kube-vip/kube-vip-daemonset.yaml"

k3s_registration_address: 10.0.0.100

