k3s_state: installed
k3s_release_version: v1.23.8+k3s2
k3s_become: true
k3s_build_cluster: true

# i really want only one master node. :-)
k3s_use_unsupported_config: true


k3s_server:
  datastore-endpoint: "mysql://k3s:{{ datastore_password }}@tcp(192.168.0.3:3307)/k3s"
  disable:
    - local-storage
    - traefik
    - servicelb

k3s_server_manifests_urls:
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml

k3s_server_manifests_templates:
  - "manifests/kube-vip/kube-vip-daemonset.yaml"


k3s_registration_address: 192.168.0.119

