---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          cpu: 32m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 512Mi
    vpa:
      enabled: false
      updater:
        enabled: false

    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: graph
          external-dns.alpha.kubernetes.io/target: "lb.${SECRET_DOMAIN_2}" 
          external-dns.alpha.kubernetes.io/ttl: "120" 
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start

        hosts:
          - host: "goldilocks.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                type: Prefix

        tls:
          - hosts:
            - "goldilocks.${SECRET_DOMAIN_2}"
