---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-v1
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-backup