all:
  children:
    database:
      hosts:
        lb.rwcloud.org:
    loadbalancer:
      hosts:
        lb.rwcloud.org:
    master:
      hosts:
        master1.rwcloud.org:
        master2.rwcloud.org:
        master3.rwcloud.org:
    public_worker:
      hosts:
        worker1.rwcloud.org:
        worker2.rwcloud.org:
    local_worker:        
      hosts:
        pi-0:
        pi-1:
        pi-2:
        pi-3:
        pc-0:
        pc-1:
    worker:
      children:
        public_worker:
        local_worker:
    k3s_cluster:
      children:
        master:
        public_worker:
        local_worker:
    public_nodes:
      children:
        loadbalancer:
        master:
        public_worker: 
    wireguard_peers:
      hosts:
        pi-wg:      
      children:
        public_nodes: