---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yaml  
  - metallb.yaml
  - kured.yaml
  - node-feature-discovery.yaml
  - nfs-subdir-external-provisioner.yaml
  - hass.yaml
  
  